name: danger-js
on:
  repository_dispatch:
    types: [danger-js]
jobs:
  danger-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install  --frozen-lockfile
      - name: Get PR number for branch
        id: pr-id-for-branch
        run: |
          prIdForBranch=$(gh pr view --json number --jq .number)
          echo "PR_ID_FOR_BRANCH=$prIdForBranch" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Danger
        run: yarn danger ci
        env:
          DANGER_MANUAL_CI: true
          DANGER_MANUAL_GH_REPO: ${{ github.repository }}
          DANGER_MANUAL_PR_NUM: ${{ steps.pr-id-for-branch.outputs.PR_ID_FOR_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
